// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQgX6PBSyEaPNKOmzPd6NeWRIPdFMaIog',
    appId: '1:1087276421697:android:27d508a46d27f0337a2cc0',
    messagingSenderId: '1087276421697',
    projectId: 'expense-tracker-132a9',
    storageBucket: 'expense-tracker-132a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz6OJcNHUeQ_KKPABJBm9msHhjteIW4OY',
    appId: '1:1087276421697:ios:d0f49d8ecf8dc0ef7a2cc0',
    messagingSenderId: '1087276421697',
    projectId: 'expense-tracker-132a9',
    storageBucket: 'expense-tracker-132a9.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8eVywHkX7mD60QOmB_zEnYQ8PuumtMAo',
    appId: '1:1087276421697:web:195df355bdcab0947a2cc0',
    messagingSenderId: '1087276421697',
    projectId: 'expense-tracker-132a9',
    authDomain: 'expense-tracker-132a9.firebaseapp.com',
    storageBucket: 'expense-tracker-132a9.firebasestorage.app',
    measurementId: 'G-VF8NNQKWSK',
  );

}